// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-variants/MinimalBottomSheet.tsx": () => import("../components/mockups/login-variants/MinimalBottomSheet.tsx"),
  "./components/mockups/login-variants/SplitCard.tsx": () => import("../components/mockups/login-variants/SplitCard.tsx"),
  "./components/mockups/login-variants/StackedHero.tsx": () => import("../components/mockups/login-variants/StackedHero.tsx")
};
